### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by diliboy88** [mu-editor/crash-reports#180]
[**REMEMBER]) TO ATTACH YOUR LOG FILE**
[mu.log](https://github.com/mu-editor/mu/files/7780375/mu.log)

Version: 1.1.0b7
Locale: en_GB
Platform: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

```
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 760, in on_ls_fail
    self.disable()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted

```

**Comment by carlosperate** [comment]
Hi @diliboy88, thanks for the report and the log.

I believe this issue has been fixed already, but we haven't done a release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could **uninstall the previous version of Mu** before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/2697356255

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4189262/182040197-23964238-e5e0-4ffb-a441-6ed1150d48e0.png">

**Comment by carlosperate** [comment]
Thanks for the report @diliboy88 !

The new Mu Editor v1.2.0 released yesterday fixes this issue, if you download the latest installer for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be able to look into that issue 👍

Thanks again!
