### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by choiiiiiiiii** [mu-editor/crash-reports#244]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: ko_KR
Platform: Windows 10 10.0.19044 AMD64

```
ped_wheels_filepath)
  File "C:\Users\Choi Yeoeun\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 860, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Choi Yeoeun\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Choi Yeoeun\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Choi Yeoeun\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Choi Yeoeun\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Choi Yeoeun\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Choi Yeoeun\AppData\Local\python\mu\mu_venv-38-20220811-164706\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\Public\Documents\ESTsoft\CreatorTemp\tmpny0s18on\asttokens-2.0.5-py2.py3-none-any.whl'

```

**Comment by choiiiiiiiii** [comment]
When the mu editor starts after installation, this error appears.
How do you solve it?

**Comment by carlosperate** [comment]
Hi @choiiiiiiiii, thanks for the report.

I believe this issue has been fixed already, but we haven't done a release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could uninstall the previous version of Mu before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/2697356255

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4189262/182040197-23964238-e5e0-4ffb-a441-6ed1150d48e0.png">

**Comment by carlosperate** [comment]
Thanks for the report @choiiiiiiiii  ! 

The new Mu Editor v1.2.0 release yesterday fixes this issue, if you install the latest version for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be happy to look into that issue 👍

Thanks again!
