### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by FameAmy** [mu-editor/crash-reports#318]
**REMEMBER TO ATTACH YOUR LOG FILE**
mentError: Process finished but with error code 101:

**Comment by carlosperate** [comment]
Hi @FameAmy, thanks for the report!

There has been a few fixes recently that have not been release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could **uninstall the previous version of Mu** before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/3235316433

<img width="1092" alt="Screenshot 2022-10-21 at 13 13 28" src="https://user-images.githubusercontent.com/4189262/197193169-427a2669-44e3-4b4b-8b6e-3e5431d3724c.png">

**Comment by carlosperate** [comment]
Thanks for the report @FameAmy  ! 

The new Mu Editor v1.2.0 release yesterday fixes this issue, if you install the latest version for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be happy to look into that issue 👍

Thanks again!
