### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Phachradanai** [mu-editor/crash-reports#324]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: th_TH
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\acer SP4750 LP_DEW\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 760, in on_ls_fail
    self.disable()
  File "C:\Users\acer SP4750 LP_DEW\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted

```

**Comment by carlosperate** [comment]
Hi @Phachradanai, thanks for the report!

There has been a few fixes recently that have not been release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could **uninstall the previous version of Mu** before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/3235316433

<img width="1092" alt="Screenshot 2022-10-21 at 13 13 28" src="https://user-images.githubusercontent.com/4189262/197193169-427a2669-44e3-4b4b-8b6e-3e5431d3724c.png">

**Comment by carlosperate** [comment]
Thanks for the report @Phachradanai!

The new Mu Editor v1.2.0 released yesterday fixes this issue, if you download the latest installer for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be able to look into that issue 👍

Thanks again!
